services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      LISTEN_PORT: "8080"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      OSRM_API_URL: "http://osrm:5000/"
    ports:
      - "127.0.0.1:9081:8080"

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:9080:8080"

  map:
    build:
      context: ../map-v2
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "127.0.0.1:9082:80"

  osrm:
    build:
      context: ./osrm
    restart: unless-stopped
    ports:
      - "127.0.0.1:9083:5000"
